---
title: "latex_formulas"
author: "Will Simmons"
date: "11/5/2019"
output: github_document
---

```{r}
# these are constructed at https://www.codecogs.com/latex/eqneditor.php
```


$$
(1) \hspace{20mm} log\{E({Y_i)}\} = \beta_0 + f(X_{i1}) + g(X_{i2}) + \beta_1X_{i3} + log(n_i) \\
\hspace{20mm}\\
\hspace{20mm} \text{Where: }\\
\hspace{20mm} n_i = \text{offset}\\
\hspace{20mm}f(X_{i1}) = \text{Fourier function for seasonal wasting trend}\\
\hspace{20mm}g(X_{i2}) = \text{linear function for long-term wasting trend}\\
\hspace{20mm}X_{i3} = \text{precipitation}\ (mm)
$$

$$
(2) \hspace{20mm} log\{E({Y_i)}\} = \beta_0 + f(X_{i1}) + g(X_{i2}) + \beta_1X_{i3} + log(n_i) \\
\hspace{20mm}\\
\hspace{20mm} \text{Where: }\\
\hspace{20mm} n_i = \text{offset}\\
\hspace{20mm}f(X_{i1}) = \text{Fourier function for seasonal wasting trend}\\
\hspace{20mm}g(X_{i2}) = \text{linear function for long-term wasting trend}\\
\hspace{20mm}X_{i3} = \text{maximum temperature}\ (^{\circ}C)
$$


$$
(3) \hspace{20mm} log\{E({Y_i)}\} = \beta_0 + f(X_{i1}) + g(X_{i2}) + \beta_1X_{i3} + log(n_i) \\
\hspace{20mm}\\
\hspace{20mm} \text{Where: }\\
\hspace{20mm} n_i = \text{offset}\\
\hspace{20mm}f(X_{i1}) = \text{Fourier function for seasonal wasting trend}\\
\hspace{20mm}g(X_{i2}) = \text{linear function for long-term wasting trend}\\
\hspace{20mm}X_{i3} = \text{minimum temperature}\ (^{\circ}C)
$$
$$
\\\hspace{18mm}\beta_2X_{2ij}\\
\\
\hspace{20mm} \text{Where: }\\
\hspace{20mm}X_{2ij} = \text{past 24-hour diarrhea}\ (1=yes, 0=no)
$$

```{r}
## new one with stacked bracket for weather terms
```

$$
(1) \hspace{20mm} log\{E({Y_{ij})}\} = \beta_0 + f(x_i) + g(x_i) + \beta_1X_{1ij} + log(n_{ij}) \\
\hspace{20mm}\\
\hspace{20mm} \text{Where: }\\
\hspace{20mm}f(x_i) = \text{Fourier function for seasonal wasting trend for area \textit{i}}\\
\hspace{20mm}g(x_i) = \text{linear function for long-term wasting trend for area \textit{i}}\\
\hspace{20mm}X_{1ij} = \begin{cases}\text{precipitation}\ (mm) \text{ for area \textit{i}, observation \textit{j}}
\\ \text{minimum temperature}\ (^{\circ}C) \text{ for area \textit{i}, observation \textit{j}}
\\ \text{maximum temperature}\ (^{\circ}C) \text{ for area \textit{i}, observation \textit{j}}
\end{cases}\\
\hspace{20mm} n_{ij} = \text{offset for area \textit{i}, observation \textit{j}}\\ 
$$